name: Deploy Infrastructure Steps

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      lambda_version:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # loading environment variables from .github/workflows/env_vars/<environment>/env_vars.json
      # the reason why is because we can set the vars once and use them in multiple pipelines
      - name: Load environment configuration
        id: load-env
        run: |
          CONFIG_FILE=".github/workflows/env_vars/${{ inputs.environment }}/env_vars.json"
          echo "Loading environment variables from $CONFIG_FILE"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "âŒ Config file not found: $CONFIG_FILE"
            exit 1
          fi

          cat $CONFIG_FILE | jq -r 'to_entries | .[] | "echo \(.key)=\(.value) >> $GITHUB_ENV"' | bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}/app"
          echo "Running tests in app/tests..."
          python -m unittest discover -s app/tests -p "test_*.py"

      - name: Set up AWS CLI with OIDC Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push lambda image
        run: |
          LAMBDA_TAG=${{ inputs.lambda_version }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}

          # LAMBDA_TAG="$1"
          # ECR_REPO="$2"
          # REGISTRY="$3"
          # LAMBDA_PATH="$4"
          chmod +rwx ./.github/scripts/build_push_image_to_ecr.sh
          ./.github/scripts/build_push_image_to_ecr.sh $LAMBDA_TAG $ECR_REPO_LAMBDA $REGISTRY app
          
          LAMBDA_TAG=${{ inputs.lambda_version }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}

          if aws ecr describe-images --repository-name=$ECR_REPO_LAMBDA --image-ids=imageTag=$LAMBDA_TAG; then
              echo "Image already exists. Skipping build and push."
          else
              echo "Image not found. Building and pushing..."
              docker build -t $ECR_REPO_LAMBDA:$LAMBDA_TAG app
              docker tag $ECR_REPO_LAMBDA:$LAMBDA_TAG $REGISTRY/$ECR_REPO_LAMBDA:$LAMBDA_TAG
              docker push $REGISTRY/$ECR_REPO_LAMBDA:$LAMBDA_TAG
          fi
          # export the image URI to be used in Terraform
          echo "LAMBDA_IMAGE=$REGISTRY/$ECR_REPO_LAMBDA:$LAMBDA_TAG" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform-infrastructure
        run: |
          terraform init \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=${TF_BACKEND_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_DYNAMODB_TABLE}"

      - name: Terraform Plan
        working-directory: terraform-infrastructure
        run: |
          terraform plan \
            -var="region=${AWS_REGION}" \
            -var="project_name=${TF_PROJECT_NAME}" \
            -var="environment=${{ inputs.environment }}" \
            -var="lambda_image=${LAMBDA_IMAGE}"

      - name: Terraform Apply
        working-directory: terraform-infrastructure
        run: |
          terraform apply -auto-approve \
            -var="region=${AWS_REGION}" \
            -var="project_name=${TF_PROJECT_NAME}" \
            -var="environment=${{ inputs.environment }}" \
            -var="lambda_image=${LAMBDA_IMAGE}"

      - name: Get Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs-${{ inputs.environment }}
          path: terraform-infrastructure/outputs.json
          retention-days: 1
