name: infrastructure-pipeline

on:
  push:
    tags: ['dev-v*', 'prod-v*']
  workflow_dispatch:
    inputs:
      lambda_version:
        description: 'Lambda/app version to deploy (e.g., dev-v1.0.0)'
        required: true
        default: 'dev-v1.0.0'
        type: string

env:
  AWS_REGION: eu-west-2
  TF_BACKEND_BUCKET: terraform-state-department-name-serverless-project
  TF_BACKEND_KEY: terraform.tfstate
  TF_DYNAMODB_TABLE: terraform-lock-table-serverless-project
  TF_PROJECT_NAME: project-name
  ENV: ${{ inputs.environment }}
  LAMBDA_ARTIFACTS_BUCKERT: ${{ TF_PROJECT_NAME }}-list-s3-contents-lambda-code-s3

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploying ${{ github.ref_name }} version
    uses: ./.github/workflows/deploy_infrastructure.yaml
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/prod-v') && 'prod' || 'dev' }}
      lambda_version: ${{ github.event.inputs.lambda_version }}
      # lambda_version: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || github.event.inputs.lambda_version }}
